name: Build gfootball on Mac

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'gfootball/doc/**'
      - '*.md'
      - '.dockerignore'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-10.15, macos-latest ]
    steps:
      - name: Check out football repository
        uses: actions/checkout@v2

      - name: Install brew dependencies
        run: brew install python3 cmake sdl2 sdl2_image sdl2_ttf sdl2_gfx boost boost-python3

      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel build psutil
          python3 -m pip install -r requirements.txt

      - name: Build package
        run: python3 -m build --no-isolation --wheel
